version: "3.9"
services:
  database:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: trx
    ports:
      - 2345:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
